config/routes.rb
Rails.application.routes.draw do
  get 'files/filesname'

  get 'say/hello'

  get 'say/goodbye'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def filesname
  	   @files = Dir.glob('*')
      return @files
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/files/filesname.html.erb
<h1>Files in the current directory</h1>

<p>
    The files in the current directory are: 
</p>
<ul>    
    <% @files.each do |file| %>
    <li> file name is: <br><%= file; %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!</h1>
<p>
	It was nice having you here.
</p>
<p>
	Say <%= link_to "Hello", say_hello_path %> again.
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>
	It is now <%= @time %>
</p>
<p>
	Time to say
	 <%= link_to "Goodbye", say_goodbye_path %>!
</p>